#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MAINFRAME                           128
#define IDR_RIBBON_COMMANDS                     129
#define IDB_ICONS                               131
#define IDB_BIGICONS                            132
#define IDR_PANE_PROGRESS                       133
#define IDR_WIA_DESC                            134
#define IDD_PHOTOMODE_STANDARD_FORM             256
#define IDD_PHOTOMODE_PANORAMA_FORM             257
#define IDD_DEVICEPROPERTYVIEW_FORM             258
#define IDD_CAMERAINFO                          259
#define IDD_ABOUTBOX                            260
#define IDD_CAMERA_ERROR                        261
#define IDD_SETTINGS                            262
#define IDD_CONNECT_CAMERA                      263
#define IDD_PHOTOMODE_HDR_FORM                  264
#define IDD_VIEWFINDER_FORM                     265
#define IDD_PHOTOMODE_HDR_PANORAMA_FORM         266
#define IDD_PHOTOMODE_TIMELAPSE_FORM            267
#define IDD_PHOTOMODE_PHOTO_STACKING_FORM       268
#define IDC_BUTTON_TIMELAPSE_START              1000
#define IDC_BUTTON_TIMELAPSE_STOP               1001
#define IDC_BUTTON_PHOTO_STACKING_START         1002
#define IDC_STATIC_ABOUT_VERSION                1024
#define IDC_STATIC_ABOUT_INFO                   1025
#define IDC_LIST_CAMERA                         1026
#define IDC_BUTTON_REFRESH                      1027
#define IDC_BUTTON_INFO                         1028
#define IDC_BUTTON_COPY                         1029
#define IDC_EDIT_INFO                           1030
#define IDC_BUTTON_RELEASE                      1031
#define IDC_COMBO_SHOOTING_MODE                 1032
#define IDC_COMBO_APERTURE                      1033
#define IDC_COMBO_SHUTTER_SPEED                 1034
#define IDC_COMBO_EXPOSURE_COMP                 1035
#define IDC_COMBO_WHITE_BALANCE                 1036
#define IDC_EDIT_ERROR_MESSAGE                  1037
#define IDC_EDIT_ERROR_DETAILS                  1038
#define IDC_EDIT_SETTING_PROJECTS_FOLDER        1039
#define IDC_BUTTON_SETTING_PROJECTS_FOLDER      1040
#define IDC_CHECK_SETTING_CURRENT_DATE_FOLDER   1041
#define IDC_CHECK_SETTING_IMAGE_TYPE_FOLDER     1042
#define IDC_CHECK_SETTING_LOG_FOLDER            1043
#define IDC_EDIT_SETTING_LOG_FOLDER             1044
#define IDC_BUTTON_SETTINGS_LOG_FOLDER          1045
#define IDC_EDIT_SETTINGS_PATH_PHOTOMATIX       1046
#define IDC_BUTTON_SETTINGS_DETECT_PHOTOMATIX   1047
#define IDC_EDIT_SETTINGS_PATH_HUGIN            1048
#define IDC_BUTTON_SETTINGS_DETECT_HUGIN        1049
#define IDC_BUTTON_AEB                          1050
#define IDC_COMBO_AEB_BRACKET_SHOTS             1051
#define IDC_LIST_AEB_SHUTTER_SPEED_VALUES       1052
#define IDC_BUTTON_PANORAMA_STOP                1053
#define IDC_BUTTON_PANORAMA_START               1054
#define IDC_BUTTON_PANORAMA_CANCEL              1055
#define IDC_SLIDER_ZOOM                         1059
#define IDC_STATIC_VIEWFINDER_FRAME             1065
#define IDC_CAMERA_RELEASE                      1066
#define IDC_RADIO_TIMELAPSE_RELEASE_TRIGGER_INTERVAL 1067
#define IDC_RADIO_TIMELAPSE_RELEASE_TRIGGER_POST_TRANSFER 1068
#define IDC_RADIO_TIMELAPSE_RELEASE_TRIGGER_MANUAL 1069
#define IDC_DATETIMEPICKER_TIMELAPSE_RELEASE_TRIGGER_INTERVAL 1070
#define IDC_CHECKBOX_TIMELAPSE_SCHEDULE_STARTTIME 1071
#define IDC_DATETIMEPICKER_TIMELAPSE_SCHEDULE_START_DATE 1072
#define IDC_DATETIMEPICKER_TIMELAPSE_SCHEDULE_START_TIME 1073
#define IDC_CHECKBOX_TIMELAPSE_SCHEDULE_ENDTIME 1074
#define IDC_DATETIMEPICKER_TIMELAPSE_SCHEDULE_END_DATE 1075
#define IDC_DATETIMEPICKER_TIMELAPSE_SCHEDULE_END_TIME 1076
#define IDC_CHECKBOX_TIMELAPSE_CREATE_MOVIE_FORMAT 1077
#define IDC_COMBO_TIMELAPSE_CREATE_MOVIE_FORMAT 1078
#define IDC_CHECKBOX_TIMELAPSE_OPTIONS_AUTOADJUST_TV 1079
#define IDC_COMBO_TIMELAPSE_OPTIONS_AUTOADJUST_TV 1080
#define IDC_CHECKBOX_TIMELAPSE_OPTIONS_HDRMODE  1081
#define IDC_EDIT_SETTINGS_PATH_FFMPEG           1082
#define IDC_BUTTON_SETTINGS_FFMPEG_FOLDER       1083
#define ID_HOME_CONNECT                         32768
#define ID_HOME_SETTINGS                        32769
#define ID_PHOTO_MODE_NORMAL                    32770
#define ID_PHOTO_MODE_HDR                       32771
#define ID_PHOTO_MODE_PANO                      32772
#define ID_PHOTO_MODE_HDR_PANO                  32773
#define ID_PHOTO_MODE_TIMELAPSE                 32774
#define ID_PHOTO_MODE_PHOTOSTACK                32775
#define ID_PHOTO_MODE_SCRIPTING                 32776
#define ID_PHOTO_MODE_DEVICE_PROPERTIES         32777
#define ID_PHOTO_MODE_IMAGE_PROPERTIES          32778
#define ID_PHOTO_MODE_CAMERA_FILE_SYSTEM        32779
#define ID_PREV_IMAGES_SHOW                     32780
#define ID_PREV_IMAGES_EXIT                     32781
#define ID_PREV_IMAGES_PREV                     32782
#define ID_PREV_IMAGES_NEXT                     32783
#define ID_PREV_IMAGES_OPEN_FOLDER              32784
#define ID_PREV_IMAGES_EDIT                     32785
#define ID_PREV_IMAGES_OVERLAY_IMAGE            32786
#define ID_CAMERA_RELEASE                       32787
#define ID_CAMERA_SHOOTING_MODE                 32788
#define ID_CAMERA_SETTINGS_AV                   32789
#define ID_CAMERA_SETTINGS_TV                   32790
#define ID_CAMERA_SETTINGS_EXPOSURE             32791
#define ID_CAMERA_SETTINGS_ISO                  32792
#define ID_CAMERA_SETTINGS_SAVETO               32793
#define ID_CAMERA_SETTINGS_SAVETO_CAMERA        32794
#define ID_CAMERA_SETTINGS_SAVETO_PC            32795
#define ID_CAMERA_SETTINGS_SAVETO_BOTH          32796
#define ID_CAMERA_SETTINGS_IMAGE_FORMAT         32797
#define ID_VIEWFINDER_SHOW                      32798
#define ID_VIEWFINDER_AUTO_FOCUS                32799
#define ID_VIEWFINDER_AUTO_WB                   32800
#define ID_VIEWFINDER_ZOOM_IN                   32801
#define ID_VIEWFINDER_ZOOM_OUT                  32802
#define ID_VIEWFINDER_LINES_MODE                32803
#define ID_VIEWFINDER_LINES_MODE_NONE           32804
#define ID_VIEWFINDER_LINES_MODE_RULEOFTHIRDS   32805
#define ID_VIEWFINDER_LINES_MODE_GOLDENRATIO    32806
#define ID_VIEWFINDER_OUTPUT_TYPE               32807
#define ID_VIEWFINDER_OUTPUT_TYPE_LCD           32808
#define ID_VIEWFINDER_OUTPUT_TYPE_VIDEO_OUT     32809
#define ID_VIEWFINDER_OUTPUT_TYPE_OFF           32810
#define ID_VIEWFINDER_SHOW_OVEREXPOSED          32811
#define ID_VIEWFINDER_SHOW_OVERLAY_IMAGE        32812
#define ID_VIEWFINDER_HISTOGRAM                 32813
#define ID_SCRIPTING_OPEN                       32814
#define ID_SCRIPTING_RELOAD                     32815
#define ID_SCRIPTING_RUN                        32816
#define ID_SCRIPTING_STOP                       32817
#define ID_SCRIPTING_EDIT                       32818
#define ID_VIEW_RIBBON                          0xE804
