#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MAINFRAME                           128
#define IDR_PANE_PROGRESS                       129
#define IDR_WIA_DESC                            130
#define IDB_ICONS                               131
#define IDB_BIGICONS                            132
#define IDD_PHOTOMODE_STANDARD_FORM             256
#define IDD_PHOTOMODE_PANORAMA_FORM             257
#define IDD_DEVICEPROPERTYVIEW_FORM             258
#define IDD_CAMERAINFO                          259
#define IDD_ABOUTBOX                            260
#define IDD_CAMERA_ERROR                        261
#define IDD_SETTINGS                            262
#define IDD_CONNECT_CAMERA                      263
#define IDD_PHOTOMODE_HDR_FORM                  264
#define IDD_VIEWFINDER_FORM                     265
#define IDC_STATIC_ABOUT_VERSION                1024
#define IDC_STATIC_ABOUT_INFO                   1025
#define IDC_LIST_CAMERA                         1026
#define IDC_BUTTON_REFRESH                      1027
#define IDC_BUTTON_INFO                         1028
#define IDC_BUTTON_COPY                         1029
#define IDC_EDIT_INFO                           1030
#define IDC_BUTTON_RELEASE                      1031
#define IDC_COMBO_SHOOTING_MODE                 1032
#define IDC_COMBO_APERTURE                      1033
#define IDC_COMBO_SHUTTER_SPEED                 1034
#define IDC_COMBO_EXPOSURE_COMP                 1035
#define IDC_COMBO_WHITE_BALANCE                 1036
#define IDC_EDIT_ERROR_MESSAGE                  1037
#define IDC_EDIT_ERROR_DETAILS                  1038
#define IDC_EDIT_SETTING_PROJECTS_FOLDER        1039
#define IDC_BUTTON_SETTING_PROJECTS_FOLDER      1040
#define IDC_CHECK_SETTING_CURRENT_DATE_FOLDER   1041
#define IDC_CHECK_SETTING_IMAGE_TYPE_FOLDER     1042
#define IDC_CHECK_SETTING_LOG_FOLDER            1043
#define IDC_EDIT_SETTING_LOG_FOLDER             1044
#define IDC_BUTTON_SETTINGS_LOG_FOLDER          1045
#define IDC_EDIT_SETTINGS_PATH_PHOTOMATIX       1046
#define IDC_BUTTON_SETTINGS_DETECT_PHOTOMATIX   1047
#define IDC_EDIT_SETTINGS_PATH_HUGIN            1048
#define IDC_BUTTON_SETTINGS_DETECT_HUGIN        1049
#define IDC_BUTTON_AEB                          1050
#define IDC_COMBO_AEB_BRACKET_SHOTS             1051
#define IDC_LIST_AEB_SHUTTER_SPEED_VALUES       1052
#define IDC_BUTTON_PANORAMA_STOP                1053
#define IDC_BUTTON_PANORAMA_START               1054
#define IDC_BUTTON_PANORAMA_CANCEL              1055
#define IDC_BUTTON_VIEWFINDER_AUTOFOCUS         1056
#define IDC_BUTTON_VIEWFINDER_AUTOWHITEBALANCE  1057
#define IDC_BUTTON_ZOOM_OUT                     1058
#define IDC_SLIDER_ZOOM                         1059
#define IDC_BUTTON_ZOOM_IN                      1060
#define IDC_COMBO_VIEWFINDER_LINESMODE          1061
#define IDC_BUTTON_VIEWFINDER_HISTOGRAM         1062
#define IDC_BUTTON_PREV_IMAGEVIEWER             1063
#define IDC_STATIC_VIEWFINDER_FRAME             1064
#define ID_HOME_CONNECT                         32768
#define ID_HOME_SETTINGS                        32769
#define ID_PHOTO_MODE_NORMAL                    32770
#define ID_PHOTO_MODE_HDR                       32771
#define ID_PHOTO_MODE_PANO                      32772
#define ID_PHOTO_MODE_HDR_PANO                  32773
#define ID_PHOTO_MODE_TIMELAPSE                 32774
#define ID_PHOTO_MODE_PHOTOSTACK                32775
#define ID_PHOTO_MODE_SCRIPTING                 32776
#define ID_PHOTO_MODE_DEVICE_PROPERTIES         32777
#define ID_PHOTO_MODE_IMAGE_PROPERTIES          32778
#define ID_VIEWFINDER_SHOW                      32779
#define ID_SCRIPT_RUN                           32780
#define ID_SCRIPT_STOP                          32781
